table retail_price_optimization_dataset
	lineageTag: 6dfab051-2193-4420-9c96-81021d510a00

	measure TotalRevenue = ```
			
			SUMX(
			    retail_price_optimization_dataset,
			    retail_price_optimization_dataset[Units Sold] * retail_price_optimization_dataset[Selling Price]
			)
			
			```
		lineageTag: cb5806dd-168b-4d60-8789-faa4d085d0ae

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Product ID'
		dataType: string
		lineageTag: 3c881e4b-def6-4863-bd86-684af5f0bff1
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: d268488c-a4b3-4b2f-8d8e-3351add82006
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 0611a136-d36c-4f17-aa32-fba363d6b408
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'MRP (Maximum Retail Price)'
		dataType: double
		lineageTag: 4a21c156-d5a5-4ce0-8ae7-a8d249d64ec8
		summarizeBy: sum
		sourceColumn: MRP (Maximum Retail Price)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Selling Price'
		dataType: double
		lineageTag: e6957e33-b52a-4446-b727-914c9e4a82f3
		summarizeBy: sum
		sourceColumn: Selling Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Discount Offered (%)'
		dataType: double
		lineageTag: 062bdb63-0be7-4d97-ac00-945d8f73d576
		summarizeBy: sum
		sourceColumn: Discount Offered (%)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Units Sold'
		dataType: int64
		formatString: 0
		lineageTag: 913786f1-774d-428a-b8b6-12b4a2ab6723
		summarizeBy: sum
		sourceColumn: Units Sold

		annotation SummarizationSetBy = Automatic

	column 'Profit Margin (%)'
		dataType: double
		lineageTag: 8afcabf2-246c-40dc-9b09-77b12796a621
		summarizeBy: sum
		sourceColumn: Profit Margin (%)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Region
		dataType: string
		lineageTag: 4e72467e-5a84-4941-b863-547f51e59a1e
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Season
		dataType: string
		lineageTag: 2ab08c22-4409-4f26-bd60-4f5224c9845d
		summarizeBy: none
		sourceColumn: Season

		annotation SummarizationSetBy = Automatic

	column 'Customer Segment'
		dataType: string
		lineageTag: 18ae289c-032f-4595-8c95-30cc446f1aac
		summarizeBy: none
		sourceColumn: Customer Segment

		annotation SummarizationSetBy = Automatic

	column 'Return Rate (%)'
		dataType: double
		lineageTag: f6dcc7d1-9379-4489-9dbd-6ac0a5848d8b
		summarizeBy: sum
		sourceColumn: Return Rate (%)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Date of Sale'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5199ee85-0c89-4873-bc09-0877f487a55c
		summarizeBy: none
		sourceColumn: Date of Sale

		variation Variation
			isDefault
			relationship: 322f4059-ae3a-4241-b187-e9547bc47ab6
			defaultHierarchy: LocalDateTable_5417c7a2-6fb4-4e14-b2ac-7f4378289fe2.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition retail_price_optimization_dataset = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\gurus\Downloads\retail_price_optimization_dataset.csv"),[Delimiter=",", Columns=13, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Product ID", type text}, {"Product Name", type text}, {"Category", type text}, {"MRP (Maximum Retail Price)", type number}, {"Selling Price", type number}, {"Discount Offered (%)", type number}, {"Units Sold", Int64.Type}, {"Profit Margin (%)", type number}, {"Region", type text}, {"Season", type text}, {"Customer Segment", type text}, {"Return Rate (%)", type number}, {"Date of Sale", type date}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

